### =============================================================
### This configuration file is used by CircleCI build server
### https://circleci.com/docs/config-sample
### =============================================================
version: 2
jobs:
  # using tox
  toxify:

      docker:
        - image: python:3.8

      steps:
        - checkout
        - run:
            name: Print environment variables
            command: |
              echo "Parameters: FAKE_MASTER: $FAKE_MASTER"
        - run:
            name: Tox build
            command: |
              pip install tox
              tox -e py37 -v -- --cov=demisto_sdk --cov-report=html
              tox -e py38 -v
        - run:
            name: Pre-commit
            command: |
              . .tox/py37/bin/activate
              pre-commit --version
              pre-commit run -a
              deactivate
        - store_artifacts:
            path: coverage_html_report
        - run:
            name: Coveralls upload
            command: |
              pip install coveralls
              coveralls
        - run:
            name: Test create content artifacts
            command: |
              . .tox/py37/bin/activate

              if [[ $CIRCLE_BRANCH != master && $FAKE_MASTER != true ]]; then
                echo "Skipping creating content artifacts on non master branch"
                exit 0
              fi

              demisto-sdk create-content-artifacts
        - run:
            name: Test create ID set
            command: |
              . .tox/py37/bin/activate

              if [[ $CIRCLE_BRANCH != master && $FAKE_MASTER != true ]]; then
                  echo "Skipping creating ID set on non master branch"
                  exit 0
              fi
              demisto-sdk create-id-set -o ./Tests/id_set.json
        - run:
            name: Deploy
            command: |
              ./demisto_sdk/utils/deploy.sh
workflows:
  version: 2
  build_and_release:
    jobs:
      - toxify:
          filters:
            tags:
              only: /^v\d+\.\d+\.\d+$/
